init_from: 'gpt2' # either 'resume' (from an out_dir) or a gpt2 variant (e.g. 'gpt2-xl')
start: "\n" # or "<|endoftext|>" or etc. Can also specify a file, use as: "FILE:prompt.txt"
out_dir: 'out-gpt2'
num_samples: 10 # number of samples to draw
max_new_tokens: 500 # number of tokens generated in each sample
temperature: 0.8 # 1.0 = no change, < 1.0 = less random, > 1.0 = more random, in predictions
top_k: 200 # retain only the top_k most likely tokens, clamp others to have 0 probability
seed: 1337

# on macbook also add
# device: 'cpu'  # run on cpu only
# device_type: 'cpu'  # run on cpu only
compile_model: False # do not torch compile the model
